### ISSUE TITLE
this is a error and other errors.. right-eg: if remaining < 0 {}

### ISSUE THREAD

**Issue by angenal** [gofiber/limiter#1]
https://github.com/gofiber/limiter/blob/b11b02f1dd5293ed4fdb43eba4089c448e94a54a/main.go#L120

**Comment by angenal** [comment]
my code:
https://github.com/angenalZZZ/gofunc/blob/master/http/fast/middleware/limiter/ratelimiter.go

**Comment by Fenny** [comment]
@angenal fixed in [`v0.0.3`](https://github.com/gofiber/limiter/releases/tag/v0.0.3)

Thanks!
